# Netlify configuration for Grean Energy Next.js application
[build]
  # Build command
  command = "npm run netlify:build"

  # Directory to publish (Next.js output with Netlify plugin)
  publish = ".next"

  # Environment variables for build
  [build.environment]
    NODE_VERSION = "18.20.4"
    NODE_ENV = "production"
    NPM_FLAGS = "--production=false"
    NEXT_TELEMETRY_DISABLED = "1"

# Next.js plugin configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle Next.js API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Fallback for client-side routing handled by Next.js plugin
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://my.spline.design https://prod.spline.design; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://my.spline.design https://prod.spline.design; media-src 'self' data:; object-src 'none'; frame-src 'self' https://my.spline.design;"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Cache fonts
[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache audio files
[[headers]]
  for = "/sounds/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"